export const ACTION_TYPES = {
    ADD_CART: 'ADD_CART',
    REMOVE_CART: 'REMOVE_CART',
    REMOVE_ALL_CART: 'REMOVE_ALL_CART',
    ADD_WISHLIST: 'ADD_WISHLIST',
    REMOVE_WISHLIST: 'REMOVE_WISHLIST',
    REMOVE_ALL_WISHLIST: 'REMOVE_ALL_WISHLIST',
}